swagger: "2.0"
info:
  title: Сервис конвертации валюты
  version: 1.0.0
  description: API сервиса Currency

schemes:
  - http
  - https

basePath: /api

tags:
  - name: Convert
    description: Конвертация

paths:
  /convert:
    post:
      summary: Конвертация валюты
      tags:
        - Convert
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          required: true
          schema:
            type: object
            required: [ from, to, value ]
            properties:
              from:
                type: string
                enum: [ "EUR", "USD", "CNY", "USDT", "USDC", "ETH" ]
                example: "USD"
              to:
                type: string
                enum: [ "EUR", "USD", "CNY", "USDT", "USDC", "ETH" ]
                example: "USDT"
              value:
                type: number
                example: "20.000"
      responses:
        400:
          description: Клиентская ошибка
          schema:
            $ref: '#/definitions/Error'
        422:
          description: Ошибка схемы запроса
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Серверная ошибка
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Успешное получение данных
          schema:
            type: object
            properties:
              result:
                type: number
                x-omitempty: false
                example: "121.000"
definitions:
  Error:
    type: object
    description: объект ошибки, обязательным является лишь поле сообщения, опционально присутствует код и ряд других полей
    required:
      - message
    properties:
      message:
        type: string
        description: текстовое описание ошибки
        example: "произошла такая-то ошибка"
      code:
        type: integer
        description: цифровой код ошибки
        example: 123
